language: node_js
node_js:
  - "6"
install:
  - npm install
  - cd spec/fixtures/app1 && npm install && cd ../../../
script:
  - npm test
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js