import { AttributeTypes } from "graphql-models";
export default [
    {
        attributes: [
            {
                model: undefined,
                name: "name",
                primaryKey: false,
                required: false,
                type: AttributeTypes.String,
            },
            {
                model: undefined,
                name: "key",
                primaryKey: true,
                required: false,
                type: AttributeTypes.String,
            },
            {
                model: undefined,
                name: "createdAt",
                primaryKey: false,
                required: false,
                type: AttributeTypes.Date,
            },
            {
                model: undefined,
                name: "updatedAt",
                primaryKey: false,
                required: false,
                type: AttributeTypes.Date,
            },
        ],
        id: "model2",
        name: "Model2",
    },
    {
        attributes: [
            {
                model: undefined,
                name: "id",
                primaryKey: true,
                required: false,
                type: AttributeTypes.Integer,
            },
            {
                model: undefined,
                name: "name",
                primaryKey: false,
                required: false,
                type: AttributeTypes.String,
            },
            {
                model: undefined,
                name: "title",
                primaryKey: false,
                required: false,
                type: AttributeTypes.String,
            },
            {
                model: undefined,
                name: "num",
                primaryKey: false,
                required: true,
                type: AttributeTypes.Integer,
            },
            {
                model: undefined,
                name: "sum",
                primaryKey: false,
                required: false,
                type: AttributeTypes.Float,
            },
            {
                model: undefined,
                name: "isActive",
                primaryKey: false,
                required: true,
                type: AttributeTypes.Boolean,
            },
            {
                model: undefined,
                name: "firstActive",
                primaryKey: false,
                required: true,
                type: AttributeTypes.Date,
            },
            {
                model: undefined,
                name: "lastActive",
                primaryKey: false,
                required: false,
                type: AttributeTypes.Date,
            },
            {
                model: "model2",
                name: "model2Field",
                primaryKey: false,
                required: false,
                type: AttributeTypes.Model,
            },
            {
                model: undefined,
                name: "createdAt",
                primaryKey: false,
                required: false,
                type: AttributeTypes.Date,
            },
            {
                model: undefined,
                name: "updatedAt",
                primaryKey: false,
                required: false,
                type: AttributeTypes.Date,
            },
        ],
        id: "modelname1",
        name: "ModelName1",
    },
];
